### PR TITLE
Provides unique user names

### PR DESCRIPTION
**Pull request by res1st**
This Keypirinha package didn't work for me at all
because the field 'name' was not set for some users.
Another problem was that that the field 'name' was
not unique and they were displayed with the name.
I had no change to guess which is the one I was looking
for. That's why I added the username to the display value.

### CODE REVIEW

**Comment by res1st** [comment]
"I had no chance to guess ..."
So the same name was shown twice.

**Comment by malys** [comment]
Great!! 
I was afraid that you abandon  your project.
I have integrated your merge request changing some lines.
Could you validate master branch? I will release it after that.

**Comment by res1st** [comment]
I was a little too busy with my family and sickness, so my pull request took a little longer. 

Your commit look fine on the master branch.
It was my first code in Python, so thank you for cleaning it up.

**Comment by malys** [comment]
Release 0.1.1 published :)

**Comment by res1st** [comment]
> Release 0.1.1 published :)

Great :)

**Pull request closed without merging**
